# Handles image operations (resize, crop, filter, combine layers) using Pillow/OpenCV.

# def apply_grayscale(...): ...
# def apply_gaussian(...): ...
# def create_rect_selection(...): ...
# def create_lasso_selection(...): ...
# def brush_stroke(...): ...
# def eraser_stroke(...): ...
